services:
  gate:
    image: ghcr.io/minekube/gate:latest
    container_name: gate
    ports:
      - "25565:25565"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: "no"
    volumes:
    - ./config.yml:/config.yml
